# Generated by Django 5.2.3 on 2025-06-23 03:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_video_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
