# Generated by Django 5.2.3 on 2025-06-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.IntegerField(default=1080),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.IntegerField(default=1920),
        ),
    ]
