# Generated by Django 5.2.3 on 2025-07-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_video_height_video_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='analyzed_images',
            field=models.JSONField(default=['unknown']),
            preserve_default=False,
        ),
    ]
