# Generated by Django 5.2.3 on 2025-12-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_analysis_analyzed_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_data',
            field=models.FileField(upload_to=''),
        ),
    ]
