# Generated by Django 5.2.3 on 2025-12-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_video_video_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='height',
        ),
        migrations.RemoveField(
            model_name='video',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='width',
        ),
        migrations.AlterField(
            model_name='video',
            name='video_data',
            field=models.FileField(upload_to='user_videos/'),
        ),
    ]
