# Generated by Django 5.2.3 on 2025-12-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_video_height_remove_video_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.IntegerField(default=1080),
        ),
        migrations.AddField(
            model_name='video',
            name='user_id',
            field=models.CharField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.IntegerField(default=1920),
        ),
    ]
