# Generated by Django 5.2.3 on 2025-12-18 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_video_height_video_user_id_video_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='height',
        ),
        migrations.RemoveField(
            model_name='video',
            name='width',
        ),
    ]
