# Generated by Django 5.2.3 on 2025-12-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_video_height_remove_video_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.IntegerField(default=1920),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.IntegerField(default=1080),
        ),
    ]
