# Generated by Django 5.2.3 on 2026-02-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_video_height_video_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='frames_cut_per_second',
            field=models.IntegerField(default=5),
        ),
    ]
