# Generated by Django 5.2.2 on 2025-06-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=20)),
                ('password', models.TextField(max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
